### ISSUE TITLE
v0.99.519 Graphic Bug Scaling

### ISSUE THREAD

**Issue by MAXBURAOT** [bolrog/d2dx#76] opened 2021-05-20 12:03 UTC
if my setting for D2DX.cfg set noresmod=false, widescreen scaling seems to be out of bound
and if i set noresmod=true, widescreen is ok no problem

```
{
    "D2DX": "PLEASE DO NOT EDIT THIS CONFIGURATION FILE. IT IS GENERATED ON EVERY STARTUP.",
    "SlashGaming Diablo II Free Resolution": {
        "!!!Metadata (Do not modify)!!!": {
            "Major Version A": 3,
            "Major Version B": 0,
            "Minor Version A": 1,
            "Minor Version B": 0
        },
        "Ingame Resolutions": [
            "640x480",
            "800x600",
            "1360x768"
        ],
        "Ingame Resolution Mode": 2,
        "Main Menu Resolution": "800x600",
        "Custom MPQ File": "d2dx_sgd2freeres.mpq",
        "Enable Screen Border Frame?": true,
        "Use Original Screen Border Frame?": false,
        "Use 800 Interface Bar?": true
    },
    "!!!Globals!!!": {
        "Config Tab Width": 4
    }
}

```

![1](https://user-images.githubusercontent.com/33173384/118977796-27023600-b9a9-11eb-8e10-381b7502a5a4.png)

![Untitled](https://user-images.githubusercontent.com/33173384/118977947-52852080-b9a9-11eb-844a-06b4050b48ce.png)

**Comment by bolrog** [comment] 2021-05-20 12:49
Does it look ok in fullscreen?

**Comment by MAXBURAOT** [comment] 2021-05-20 13:24
for full screen is ok, but i dunno why for windowed mode its like that

**Comment by tytannial** [comment] 2021-05-21 01:30
By the way, there could be a dpi fix? Windows high dpi makes game fuzzy.

**Comment by bolrog** [comment] 2021-05-21 09:36
I have disabled the effect on DPI on the game in D2DX, so this surprises me a bit. Have you noticed this?

**Comment by Yh793** [comment] 2021-05-21 11:00
Mr.bolrog
519 release `config file` scale doesn't work.
Command-line be OK.

**Comment by bolrog** [comment] 2021-05-25 19:53
Please try release 525 and see if it resolves the scaling bug for you.

**Comment by MAXBURAOT** [comment] 2021-05-26 12:26
***One significant thing i notice when i launch the game i need to wait for 30 sec to see the game, is it normal, previously i not like that maybe 2~5 sec only

Using D2DX v0.99.526b, D2 v1.14d, Desktop Display Resolution = 1360x768
Using 1360x768 Resolution (97% Scaling)
D2DX.cfg is set noresmod=false and D2DX_SGD2FreeRes.json setting bellow (Automatic Set)
```
},
        "Ingame Resolutions": [
            "640x480",
            "800x600",
            "1360x768"
```
Scaling is 97% in 1360x768 and a bit blurred then i notice it showing the 2 buttons ~> New Stats / New Skills, i tested in Windowed Mode and Full Screen

** i hope for the nxt version could calculate or maximize the max resulution to achieve 100% scaling like i did below but that one the setting is different (1360x740)

![1](https://user-images.githubusercontent.com/33173384/119657953-2bbe6280-be5f-11eb-933c-a7d3c7532e82.png)
![2](https://user-images.githubusercontent.com/33173384/119658030-409af600-be5f-11eb-98f6-b0dc9e06732f.png)
![3](https://user-images.githubusercontent.com/33173384/119658100-55778980-be5f-11eb-8e10-41814ff81116.png)


Using D2DX v0.99.526b, D2 v1.14d, Desktop Display Resolution = 1360x768
Using 1360x740 Resolution (To Achieve 100% Scaling) <~I Just Guess this size
D2DX.cfg is set noresmod=true and D2DX_SGD2FreeRes.json setting bellow (Manual Set by me)
```
},
        "Ingame Resolutions": [
            "640x480",
            "800x600",
            "1024x720",
            "1280x720",
            "1360x720",
            "1360x740"
```
Scaling is 100% in 1360x740 and Graphics is good then i notice its not showing the 2 buttons ~> New Stats / New Skills, i tested in Windowed Mode and Full Screen


![7](https://user-images.githubusercontent.com/33173384/119658276-86f05500-be5f-11eb-89db-e0bad01ae746.png)
![8](https://user-images.githubusercontent.com/33173384/119658372-a4bdba00-be5f-11eb-88cc-e36287e64084.png)
![9](https://user-images.githubusercontent.com/33173384/119658229-7a6bfc80-be5f-11eb-95d8-a05324201c2c.png)

**Comment by bolrog** [comment] 2021-05-26 12:29
Yeah I have considered doing something more dynamic for the windowed mode. The problem is I don't know how the game will react to changing resolution mid game. D2 is unstable when doing that too quickly.

Regarding the 30 seconds, no that is not normal!
I'll see if I can replicate that. No other mods?

**Comment by MAXBURAOT** [comment] 2021-05-26 13:08
> Yeah I have considered doing something more dynamic for the windowed mode. The problem is I don't know how the game will react to changing resolution mid game. D2 is unstable when doing that too quickly.
> 
> Regarding the 30 seconds, no that is not normal!
> I'll see if I can replicate that. No other mods?

i did test also with SGGL and without SGGL using normal parameter -w -3dfx, and still the same need to wait 30 sec for the game to launch

**Comment by bolrog** [comment] 2021-05-29 19:06
I'm not sure how to debug this, since I'm not seeing the problem here. Maybe it's resolved with a system restart?

**Comment by MAXBURAOT** [comment] 2021-06-01 15:13
loading issue is fixed in v0.99.529, BTW below pik is noresmod=false

![7](https://user-images.githubusercontent.com/33173384/120347428-d981b380-c32e-11eb-834b-7e70a58e40fc.png)

**Comment by bolrog** [comment] 2021-06-01 19:16
Thanks for checking. Yeah that looks normal. The aspect ratio of the game itself is the same in fullscreen as in windowed mode, so there needs to be black bars on the sides because of the window title bar (and start-bar).

**Comment by bolrog** [comment] 2021-06-06 13:21
Closing for now. Feel free to reopen the issue if there are further things to address. There is a current limitation that is that fullscreen and windowed game size is the same. Maybe this can be made more flexible in the future, not sure yet.

**Closed by bolrog** 2021-06-06 13:21 UTC
Labels: bug
