### ISSUE TITLE
Some graphics elements are jittery with MoP (0.99.504)

### ISSUE THREAD

**Issue by eleriaqueen** [bolrog/d2dx#42] opened 2021-05-04 20:43 UTC
Video showing this bug occuring with player corpses : https://vimeo.com/545206266

**Comment by fapmilk** [comment] 2021-05-04 23:23
The same thing occurs with non-static text such as items on the ground, waypoints, doors, and npc names. The issue becomes more pronounced as you increase fps. When capped to 25 fps, even with the high fps / motion prediction enabled, the problem is eliminated. At 50 fps the "jitter" is noticeable but fairly subtle. At 240 fps on a 240 Hz display the issue is very apparent and text is quite blurry and difficult to read when in motion.

Even with this issue, having the option to run the game above 25 fps is a huge quality of life improvement. Really great work on this project!

**Comment by eleriaqueen** [comment] 2021-05-05 08:18
Paladin auras also exhibit what appearsto be a similar issue : https://vimeo.com/545379622

**Comment by eleriaqueen** [comment] 2021-05-05 13:58
Diablo 2 potions should not be shaken like a bottle of Orangina ! Hashtag PotionsLivesMatter.

Kidding aside, content of belt rows other than the first one shake when moving the player character :
https://vimeo.com/545495154

**Comment by 0x4e44** [comment] 2021-05-05 14:42
> Diablo 2 potions should not be shaken like a bottle of Orangina ! Hashtag PotionsMatter.
> 
> Kidding aside, content of belt rows other than the first one shake when moving the player character :
> https://vimeo.com/545495154

Had the same issue , just finished recording it. Same issue with latest version & mop activated

**Comment by bolrog** [comment] 2021-05-05 19:36
Great reports, thanks!

"Hover text" for items on the ground should be moved along with the ground, but hover text for inventory items should not, and it's hard to separate the two. Right now I don't move it along with the ground, so it "jumps" in 25 fps steps. I may be able to find a way to fix it by intercepting deeper in the game code.. not sure yet.

Paladin auras and belt items should be fixed in 505b.

**Comment by eleriaqueen** [comment] 2021-05-05 20:03
Yep auras and belt seem fixed to me in 505b.
About the shaky raindrops-hitting-water, have you found a way to make them less... shaky ? I'm wondering if they could be "missiles", because there's an effect that's sort of bubbles going up to the surface in Act 3 and that one doesn't shake probably because it's baked into the map (?)

**Comment by bolrog** [comment] 2021-05-06 07:14
Good question, I haven't examined the raindrops yet to figure out how they're done, but D2DX probably mistakenly classifies them as UI (pinning their position on screen) when they should be moved along with the world instead.

**Comment by bolrog** [comment] 2021-05-08 13:56
Found a way to identify the rain splashes.

**Comment by bolrog** [comment] 2021-05-08 14:03
I think only the item texts remain now from this issue.

There is one problem I have to solve with item texts even if I figure out how to separate them from other UI text: when they hit the edge of the screen, the game will push them in so that they aren't cut off. If I move the item texts smoothly, they will jump around a bit near the edge of the screen. I'll look into this some more.

**Comment by eleriaqueen** [comment] 2021-05-08 14:38
Can confirm rain splashes seem to behave nicely now.

**Comment by bolrog** [comment] 2021-05-16 18:44
I've added initial attempt at MoP for texts now. I'll try to iron out the last kinks moving forward, including the shadows that sometimes seem to "lose connection" with the player model and begin shaking.

What class did you play when it happened?

**Comment by eleriaqueen** [comment] 2021-05-18 18:26
Just tested latest release (518b) with Amazon and Paladin, Ama's shadow seemed ok, but Paladin's shadow seems "disconnected and shaky" right when starting a game.

**Comment by bolrog** [comment] 2021-05-18 19:00
Hmm, weird. Which game version was this?

**Comment by eleriaqueen** [comment] 2021-05-18 20:03
1.13c

**Comment by bolrog** [comment] 2021-05-18 20:04
Thanks, i'll try that

**Comment by eleriaqueen** [comment] 2021-05-18 20:06
I just created 1 of each and of all only Paladin's shadow is shaky right from the start

**Comment by bolrog** [comment] 2021-05-18 20:07
Any particular options you're using? I just tried creating a Paladin and the shadow is fine for me. Hmm.

**Comment by eleriaqueen** [comment] 2021-05-18 20:09
only '-3dfx-' other than that I disabled perspective and uh (cat is needing attention lol having problems writing) ... Lighting Quality  is High, blended shadows are on.

**Comment by bolrog** [comment] 2021-05-26 07:09
Please see if this is fixed in the latest release. :)

**Comment by eleriaqueen** [comment] 2021-05-27 06:10
I did a quick test, and Paladin shadow is stable now. Thanks!

**Closed** 2021-05-31 10:20 UTC
Labels: bug
